### ISSUE TITLE
Cannot solve CVRP problem 

### ISSUE THREAD

**Issue by silent790** [ben-hudson/pylkh#4]
hi, I installed this package and tried the example code, but the output seems to be a tsp result. Could you please help me out?

the example code is as follow:
'import requests
import lkh
problem_str = requests.get('http://vrp.atd-lab.inf.puc-rio.br/media/com_vrp/instances/A/A-n32-k5.vrp').text
problem = lkh.LKHProblem.parse(problem_str)
solver_path = r'/home/ubuntu/LKH_3/LKH-3.0.7/LKH'
print(lkh.solve(solver_path, problem=problem, max_trials=1000, runs=1, tour_file="./tour.txt"))'

the result is
`[[1, 30, 19, 9, 10, 23, 16, 11, 26, 6, 21, 33, 27, 8, 14, 18, 20, 32, 22, 35, 7, 4, 3, 24, 5, 12, 29, 15, 34, 25, 28, 36, 13, 2, 17, 31]]`

not like the README file. would you please check if some code was changed ? And how can I fix this.

**Comment by ben-hudson** [comment]
There seems to be a problem with the solution parsing. [This commit](https://github.com/ben-hudson/pylkh/tree/861717d7d4f98a6adfb567f11772802afe1cd30e) should work as expected.

**Comment by ben-hudson** [comment]
5d03d0e573f4c5785667075a05197501fc97fb56 should fix this!
