### ISSUE TITLE
Parsing error with m1_pdtsp/m_pdtsp problems

### ISSUE THREAD

**Issue by FPCalligarich** [ben-hudson/pylkh#7]
Hello, 
trying to solve m-pdtsp( and m1_pdtsp) instances I run into the error: "ParsingError: IntegerField(CAPACITY): func transformer error: invalid literal for int() with base 10: '17\nDEMAND_"  so it seems like it reads without recognizing the two lines capacity and demand dimension, it seems also that later it is also having the same parsing problem in the demand section. is m_pdtsp a kind of problem not supported? what should be done differently?

the instance used is:
NAME : m2n30Q17s777c1
TYPE : m-PDTSP
DIMENSION : 30
CAPACITY : 17
DEMAND_DIMENSION : 2
EDGE_WEIGHT_TYPE : EUC_2D
NODE_COORD_SECTION
1 0 0
2 -108 76
3 372 -432
4 -57 388
5 286 409
6 424 169
7 58 -497
8 221 118
9 470 380
10 -431 -422
11 305 -58
12 457 196
13 493 269
14 281 -259
15 -172 -484
16 263 -258
17 -427 153
18 351 314
19 478 120
20 -415 -203
21 20 -92
22 113 237
23 57 447
24 -322 -129
25 253 -27
26 -387 -243
27 -72 212
28 246 -337
29 71 279
30 351 -457
DEMAND_SECTION
1 0 0 
2 4 0 
3 0 5 
4 -6 0 
5 0 0 
6 -5 0 
7 0 -1 
8 -1 0 
9 0 -10 
10 10 0 
11 0 -9 
12 -1 0 
13 0 -3 
14 4 0 
15 0 8 
16 -3 0 
17 0 -2 
18 3 0 
19 0 -6 
20 0 0 
21 0 -4 
22 1 0 
23 0 8 
24 -1 0 
25 0 -5 
26 3 0 
27 0 9 
28 0 0 
29 0 10 
30 -8 0 
DEPOT_SECTION
1 
-1
EOF

thank you in advance for any help given

**Comment by ben-hudson** [comment]
Hi, I was able to reproduce this and I'm looking in to it... it seems my implementation doesn't support the DEMAND_DIMENSION field

**Comment by ben-hudson** [comment]
Not entirely fixed yet, still working on it

**Comment by ben-hudson** [comment]
Fixed in https://github.com/ben-hudson/pylkh/releases/tag/v2.0.0
